"""add match_network_tags to policies

Revision ID: 171a3a8e4f2b
Revises: b3c4d5e6f7a8
Create Date: 2026-07-13 14:09:50.795209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171a3a8e4f2b'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add as nullable first so existing rows are not violated.
    op.add_column('policies', sa.Column('match_network_tags', sa.JSON(), nullable=True))
    # Backfill existing rows with empty array.
    op.execute("UPDATE policies SET match_network_tags = '[]' WHERE match_network_tags IS NULL")
    # Tighten to NOT NULL now that all rows have a value.
    op.alter_column('policies', 'match_network_tags', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'match_network_tags')
    # ### end Alembic commands ###
