"""initial schema

Revision ID: 428b5f68373c
Revises: 
Create Date: 2026-07-11 14:42:32.503011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428b5f68373c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match_request_type', sa.String(length=100), nullable=False),
    sa.Column('match_region', sa.String(length=80), nullable=True),
    sa.Column('match_latency_zone', sa.String(length=20), nullable=True),
    sa.Column('target_service_name', sa.String(length=120), nullable=False),
    sa.Column('fallback_service_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('health_check_path', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'HEALTHY', 'DEGRADED', 'UNHEALTHY', name='servicestatus'), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('latency_zone', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='latencyzone'), nullable=False),
    sa.Column('network_tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_index(op.f('ix_services_region'), 'services', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_region'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
